<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>custom_chat_backend</RootNamespace>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Ardalis.Result" Version="10.1.0" />
        <PackageReference Include="Ardalis.Specification" Version="9.3.1" />
        <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" Version="9.3.1" />
        <PackageReference Include="AspNet.Security.OAuth.Discord" Version="10.0.0" />
        <PackageReference Include="FastEndpoints" Version="8.1.0" />
        <PackageReference Include="FastEndpoints.Swagger" Version="8.1.0" />
        <PackageReference Include="MediatR" Version="14.2.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.9" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.16.4" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Api\Services\" />
      <Folder Include="Core\Application\Common\" />
      <Folder Include="Core\Application\Features\" />
      <Folder Include="Core\Application\UseCases\User\Commands\" />
      <Folder Include="Core\Contracts\Common\" />
      <Folder Include="Core\Domain\Common\" />
      <Folder Include="Core\Domain\Enums\" />
      <Folder Include="Core\Interfaces\Auth\" />
      <Folder Include="Infrastructure\Identity\" />
      <Folder Include="Infrastructure\Persistence\Migrations\" />
    </ItemGroup>

</Project>
